### ISSUE TITLE
Support for non-multiple-accounts infrastructure

### ISSUE THREAD

**Issue by robmoorman** [labd/ecs-deplojo#6]
Some facts as I experience most of the projects I work on:

1. Most of projects are setup secure by having their own aws account (e.g. test and production separated).
2. Also in almost every case the infrastructure for test is the same for production, only smaller instance sizes and/or desired counts to minimize capacity

When having an AWS account where you have multiple environments setup in, the task definition names will conflict with each other.

A suggestion, make the configuration more abstract:

```yaml
---
clusters:
  test:
    test-example
  production:
    production-example

environments:
    test:
      DATABASE_URL: postgresql://
    production:
      DATABASE_URL: postgresql://

task_definitions:
  web: 
    template: task_definitions/web.json
    overrides:
      production:
        memory: 512

services:
  web: 
    task_definition: web

before_deploy:
  - task_definition: manage
    container: uwsgi
    command: manage.py migrate --noinput
```

Deploy with e.g. `ecs-deplojo --config example.yaml --env production --var="image=example:latest"`
