### ISSUE TITLE
Minimize configuration by placing task definitions in the same configuration

### ISSUE THREAD

**Issue by robmoorman** [labd/ecs-deplojo#7]
As #6 purposed, it can be an option to complete get rid of the separate task definitions files.
Having all configuration in one place and in YAML is maybe a better option for better maintainability.

```yaml
---
clusters:
  test:
    test-example
  production:
    production-example

environments:
    test:
      DATABASE_URL: postgresql://
    production:
      DATABASE_URL: postgresql://

task_definitions:
  web: 
    containerDefinitions:
      - name: uwsgi
        command: /usr/local/bin/uwsgi --ini /etc/uwsgi.ini
        memory: 256
        portMappings:
          - containerPort: 8080
            hostport: 0
            protocol: tcp
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-region: eu-west-1
    overrides:
      test:
        logConfiguration:
          options:
            awslogs-group: test-uwsgi
      production:
        logConfiguration:
          options:
            awslogs-group: production-uwsgi
        memory: 512

services:
  web: 
    task_definition: web

```
